services:
  postgres:
    image: timescale/timescaledb:2.15.3-pg13
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - "/env/postgres.prod.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - amr-backend-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - amr-backend-network

  amr-server:
    image: amr-server
    build: .
    restart: always
    container_name: amr-server
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    user: spring
    env_file:
      - "/env/spring.prod.env"
    networks:
      - amr-backend-network

volumes:
  postgres-data:

networks:
  amr-backend-network:
