services:
  influxdb:
    image: influxdb:2
    env_file:
      - "env/influx.env"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"

  postgres:
    image: postgres:13
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - "env/postgres.env"
    volumes:
      - postgres-data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8082:8080"
      - "50000:5000"
    user: root
    volumes:
      - /home/jenkins:/var/jenkins_home

volumes:
  influxdb-data:
  postgres-data:


