version: '3.8'

services:
  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: amr_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - amr_network

  # AMR System
  amr_system:
    build: .
    container_name: amr_system
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    networks:
      - amr_network
    restart: unless-stopped

  # Web Dashboard
  dashboard:
    build: .
    container_name: amr_dashboard
    command: ["python", "dashboard_module/web_dashboard.py"]
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    networks:
      - amr_network
    restart: unless-stopped

  # Development Environment
  dev:
    build: .
    container_name: amr_dev
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - PYTHONPATH=/app
    networks:
      - amr_network
    depends_on:
      - mosquitto

volumes:
  mosquitto_data:
  mosquitto_logs:

networks:
  amr_network:
    driver: bridge
