stages:
  - build

buildDebug:
  stage: build
  image: openjdk:17-jdk   # Android Gradle 플러그인/JDK 버전에 맞게 조정 가능
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
