planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    use_navigate_to_pose_bt: true

behavior_server:
  ros__parameters:
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/Backup"
    wait:
      plugin: "nav2_recoveries/Wait"

global_costmap:
  global_costmap:
    ros__parameters:
      resolution: 0.05
      width: 20.0
      height: 20.0
      robot_radius: 0.2

local_costmap:
  local_costmap:
    ros__parameters:
      resolution: 0.05
      width: 8.0
      height: 8.0
      robot_radius: 0.2