robot:
  ros__parameters:
    robot_name: "AMR001"
    robot_type: "autonomous_mobile_robot"
    base_frame: "base_link"
    odom_frame: "odom"
    map_frame: "map"
    robot_radius: 0.2
    wheel_separation: 0.4
    wheel_diameter: 0.1
    max_linear_velocity: 1.0
    max_angular_velocity: 2.0
    min_linear_velocity: 0.1
    min_angular_velocity: 0.1

hardware:
  ros__parameters:
    enable_motor_control: true
    enable_imu: true
    enable_camera: true
    enable_lidar: true
    enable_servo: true
    enable_led: true
    enable_battery_monitor: true

safety:
  ros__parameters:
    emergency_stop_enabled: true
    collision_detection_enabled: true
    obstacle_detection_range: 2.0
    safety_stop_distance: 0.5
    max_obstacle_height: 0.3
