spring:
  application:
    name: amr_backend
  config:
    import: optional:file:env/spring.dev.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
firebase:
  key:
    location: ${FIREBASE_KEY_LOCATION}
logging:
  level:
    com.example.amr_backend: DEBUG
mqtt:
  url: ${MQTT_URL}